INSERT INTO inventory (product_id, stock, updated_at) VALUES
                                                          (1, 50, NOW()),  -- Stock para el producto con ID 1 (ej: Polera Oversize)
                                                          (2, 40, NOW()),  -- Stock para el producto con ID 2 (ej: Polera Slim Fit)
                                                          (3, 65, NOW()),  -- Stock para el producto con ID 3 (ej: Camiseta Deportiva)
                                                          (4, 35, NOW()),  -- Stock para el producto con ID 4 (ej: Jeans Slim)
                                                          (5, 25, NOW()),  -- Stock para el producto con ID 5 (ej: Pantalón Cargo)
                                                          (6, 30, NOW()),  -- Stock para el producto con ID 6 (ej: Mom Jeans)
                                                          (7, 45, NOW()),  -- Stock para el producto con ID 7 (ej: Polerón Hoodie)
                                                          (8, 20, NOW()),  -- Stock para el producto con ID 8 (ej: Chaqueta Mezclilla)
                                                          (9, 55, NOW()),  -- Stock para el producto con ID 9 (ej: Cortaviento)
                                                          (10, 15, NOW()); -- Stock para el producto con ID 10 (ej: Zapatillas Canvas)