spring.application.name=gateway
# Fijamos el puerto central del Gateway en el 8082 (limpio y operativo)
server.port=5995

# ===================================================================
# CONFIGURACIÓN DE RUTAS DEL GATEWAY (Spring Cloud Gateway MVC)
# ===================================================================

# 1. Microservicio: Usuarios / Auth (Puerto: 8081)
spring.cloud.gateway.mvc.routes[0].id=ms-users
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/auth/**

# 2. Microservicio: Carrito (Puerto: 8082)
spring.cloud.gateway.mvc.routes[1].id=carrito
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/cart/**

# 3. Microservicio: Catálogos (Puerto: 8083)
spring.cloud.gateway.mvc.routes[2].id=catalogos
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/categories/**

# 4. Microservicio: Comprobante (Puerto: 8084)
spring.cloud.gateway.mvc.routes[3].id=comprobante
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/comprobantes/**

# 5. Microservicio: Clientes / CustomerClient (Puerto: 8085)
spring.cloud.gateway.mvc.routes[4].id=CustomerClient
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/v1/customer/**

# 6. Microservicio: Inventario / Inventory (Puerto: 8086)
spring.cloud.gateway.mvc.routes[5].id=inventory
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/v1/inventory/**

# 7. Microservicio: Notificaciones (Puerto: 8087)
spring.cloud.gateway.mvc.routes[6].id=notificaciones
spring.cloud.gateway.mvc.routes[6].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/v1/notifications/**

# 8. Microservicio: Orden / Pedidos (Puerto: 8088)
spring.cloud.gateway.mvc.routes[7].id=orden
spring.cloud.gateway.mvc.routes[7].uri=http://localhost:8088
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/v1/orders/**

# 9. Microservicio: Pagos / Payment (Puerto: 8089) - Unifique la ruta asi no esto no colapza 
spring.cloud.gateway.mvc.routes[8].id=payment
spring.cloud.gateway.mvc.routes[8].uri=http://localhost:8089
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/v1/payment/**,/api/v1/payment-methods/**

# 10. Microservicio: Productos (Puerto: 8090)
spring.cloud.gateway.mvc.routes[9].id=productos
spring.cloud.gateway.mvc.routes[9].uri=http://localhost:8090
spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/api/v1/productos/**

# ===================================================================
# CONFIGURACIONES ADICIONALES
# ===================================================================
gateway.logging.enabled=true
