spring.application.name=notificaciones
server.port=8087

# Cambiado al puerto 8081 donde se encuentra tu Gateway actual
app.gateway.url=http://localhost:5995

# Base de datos (Corregido: añadida creación automática de la DB)
spring.datasource.url=jdbc:mysql://localhost:3306/notificaciones_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes
