spring.application.name=ms-inventory
server.port= ${PORT:8083}
app.gateway.url=http://api-gateway


# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes

